# Generated by Django 5.2 on 2025-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
