# Generated by Django 5.2 on 2025-04-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailotp_alter_customuser_managers_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
