# Generated by Django 5.2 on 2025-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sellerprofile_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='opening_closing_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
