# Generated by Django 5.2 on 2025-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sellerprofile_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/customers/'),
        ),
    ]
