# Generated by Django 5.2 on 2025-04-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_customer'),
        ('users', '0007_sellerprofile_business_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_products', to='users.customerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='store.product')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
