# Generated by Django 5.2 on 2025-04-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_status_change', 'Order Status Change'), ('delivery_delay', 'Delivery Delay'), ('order_cancellation', 'Order Cancellation'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('discount_offer', 'Discount/Coupon Offer'), ('new_restaurant', 'New Restaurant Alert'), ('review_reminder', 'Review Reminder'), ('restaurant_reply', 'Restaurant Reply'), ('new_order', 'New Order Received'), ('restaurant_order_cancellation', 'Order Cancellation (Restaurant)'), ('new_review', 'New Review Posted'), ('low_stock', 'Low Stock Alert'), ('payment_received', 'Payment Received')], max_length=50),
        ),
    ]
