# Generated by Django 5.2 on 2025-05-02 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
        ('store', '0006_order_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_before', models.CharField(max_length=20)),
                ('status_after', models.CharField(max_length=20)),
                ('snapshot', models.JSONField()),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='notifications.notification')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='store.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='notificatio_order_i_2c671d_idx')],
            },
        ),
    ]
