# Generated by Django 5.2 on 2025-05-11 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_ordernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('order_status_change', 'Order Status Change'), ('delivery_delay', 'Delivery Delay'), ('order_cancellation', 'Order Cancellation'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('discount_offer', 'Discount/Coupon Offer'), ('new_restaurant', 'New Restaurant Alert'), ('review_reminder', 'Review Reminder'), ('restaurant_reply', 'Restaurant Reply'), ('new_order', 'New Order Received'), ('restaurant_order_cancellation', 'Order Cancellation (Restaurant)'), ('new_review', 'New Review Posted'), ('low_stock', 'Low Stock Alert'), ('payment_received', 'Payment Received'), ('account', 'Account Activity')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'is_read'], name='notificatio_notific_09a8d2_idx'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
