# Generated by Django 5.2 on 2025-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_deduplication_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotification',
            name='status_before',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
